repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/patrick91/pre-commit-alex
    rev: aa5da9e54b92ab7284feddeaf52edf14b1690de3
    hooks:
      - id: alex

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^tests/relay/snapshots
      - id: check-toml
